language: ruby
bundler_args: --without development
cache: bundler
before_script: "./bin/ci/before_build"
script: "bundle exec rake integration_without_recovery"
rvm:
  - "2.4.0"
  - "2.3.3"
  - "2.2"
notifications:
  email: michael@rabbitmq.com
services:
  - rabbitmq
branches:
  only:
    - master
    - 2.6.x-stable
env:
  - CI=true