bundler_args: --without development
before_script:
  - pwd
  - ls bin
  - ls bin/ci
  - ./bin/ci/before_build.sh
script: "bundle exec rspec -c spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-head
notifications:
  email: michael@defprotocol.org
branches:
  only:
    - master
    - 0.8.x-stable
    - 0.9.x-stable
    - migrate_to_amq_protocol
