language: ruby
before_install: "./bin/ci/before_install"
bundler_args: --without development
before_script: "./bin/ci/before_build"
script: "bundle exec rspec -cf documentation spec"
after_script: "/tmp/rabbitmq/sbin/rabbitmqctl stop"
rvm:
  - "2.3.0"
  - "2.2.2"
notifications:
  email: michael@rabbitmq.com
sudo: required
branches:
  only:
    - master
env:
  - RABBITMQCTL="$HOME/rabbitmq/sbin/rabbitmqctl" RABBITMQ_PLUGINS="$HOME/rabbitmq/sbin/rabbitmq-plugins"
