bundler_args: --without development
before_script: "./bin/ci/before_build.sh"
script: "bundle exec rspec -c spec"
rvm:
  - 2.0
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
  - ruby-head
  - 1.9.2
  - rbx-18mode
  - 1.8.7
notifications:
  email: michael@defprotocol.org
services:
  - rabbitmq
branches:
  only:
    - master
    - 0.9.x-stable
