bundler_args: --without development
before_script: "./bin/ci/before_build.sh"
script: "bundle exec rspec -cfs spec"
rvm:
  - "2.0"
  - "1.9.3"
  - "jruby-19mode"
  - "1.9.2"
  - "rbx-19mode"
  - "1.8.7"
notifications:
  email: michael@rabbitmq.com
services:
  - rabbitmq
branches:
  only:
    - master
    - 0.9.x-stable
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: 1.8.7
