bundler_args: --without development
before_script: ./bin/ci/before_script.sh
script: "bundle exec rspec -c spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - rbx-18mode
  - rbx-19mode
notifications:
  email: michael@novemberain.com
branches:
  only:
    - master
    - 0.8.x-stable
    - amqp_091_migration
